# Generated by Django 4.1.7 on 2023-03-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('english_title', models.CharField(max_length=100)),
                ('definition', models.TextField(blank=True, null=True)),
                ('classification', models.TextField(blank=True, null=True)),
                ('mechanism', models.TextField(blank=True, null=True)),
                ('pathophysiology', models.TextField(blank=True, null=True)),
                ('related', models.TextField(blank=True, null=True)),
                ('diagnostic_value', models.TextField(blank=True, null=True)),
                ('clinical_features', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('epidemiology', models.TextField(blank=True, null=True)),
                ('management', models.TextField(blank=True, null=True)),
                ('etiology', models.TextField(blank=True, null=True)),
                ('cause', models.TextField(blank=True, null=True)),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='SymptomsGallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
