# Generated by Django 4.1.7 on 2023-03-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('english_title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('definition', models.TextField(blank=True, null=True)),
                ('classification', models.TextField(blank=True, null=True)),
                ('pathophysiology', models.TextField(blank=True, null=True)),
                ('differential_diagnoses', models.TextField(blank=True, null=True)),
                ('clinical_features', models.TextField(blank=True, null=True)),
                ('epidemiology', models.TextField(blank=True, null=True)),
                ('etiology', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('management', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('risk_factors', models.TextField(blank=True, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('prognosis', models.TextField(blank=True, null=True)),
                ('prevention', models.TextField(blank=True, null=True)),
                ('other_names', models.TextField(blank=True, null=True)),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='SicknessGallery/')),
                ('references', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
