# Generated by Django 4.1.7 on 2023-03-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.TextField()),
                ('mainـcomplaintـPersian', models.TextField()),
                ('mainـcomplaintـenglish', models.TextField()),
                ('onset', models.TextField()),
                ('location', models.TextField()),
                ('radiation', models.TextField()),
                ('duration', models.TextField()),
                ('character', models.TextField()),
                ('associated', models.TextField()),
                ('symptom', models.TextField()),
                ('exacerbating_and_alleviating', models.TextField()),
                ('factors', models.TextField()),
                ('temporal', models.TextField()),
                ('patterns', models.TextField()),
                ('severity', models.TextField()),
                ('other_details', models.TextField()),
                ('past_medical_history', models.TextField()),
                ('medication_history', models.TextField()),
                ('family_history', models.TextField()),
                ('social_history', models.TextField()),
                ('constitutional', models.TextField()),
                ('HENT', models.TextField()),
                ('integumentary', models.TextField()),
                ('cardiovascular', models.TextField()),
                ('gastrointestinal', models.TextField()),
                ('genitourinary', models.TextField()),
                ('endocrine', models.TextField()),
                ('hematology_Oncology', models.TextField()),
                ('neurologic', models.TextField()),
                ('respiratory', models.TextField()),
                ('related_disease', models.TextField()),
                ('related_symptoms', models.TextField()),
            ],
        ),
    ]
