# Generated by Django 4.1.7 on 2023-03-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('english_title', models.CharField(max_length=100)),
                ('generic_name', models.TextField(blank=True, null=True)),
                ('english_name', models.TextField(blank=True, null=True)),
                ('pronunciation', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('other_names', models.TextField(blank=True, null=True)),
                ('brands', models.TextField(blank=True, null=True)),
                ('main_drug_category', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('mechanism_of_action', models.TextField(blank=True, null=True)),
                ('indications', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('related_treatments', models.TextField(blank=True, null=True)),
                ('related_conditions', models.TextField(blank=True, null=True)),
                ('drug_dose', models.TextField(blank=True, null=True)),
                ('different_dosage_forms', models.TextField(blank=True, null=True)),
                ('drug_interactions', models.TextField(blank=True, null=True)),
                ('food_interactions', models.TextField(blank=True, null=True)),
                ('drug_absorption', models.TextField(blank=True, null=True)),
                ('half_life', models.TextField(blank=True, null=True)),
                ('toxicity', models.TextField(blank=True, null=True)),
                ('method_of_consumption', models.TextField(blank=True, null=True)),
                ('adverse_effects', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('symptoms_of_excessive_consumption', models.TextField(blank=True, null=True)),
                ('warnings', models.TextField(blank=True, null=True)),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='MedicinesGallery/')),
                ('references', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
